build:
  id: 101
  version: 1.0.1
  name: "Production-build"
  type: "Production Build"

#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#management:
#  endpoints:
#  web:
#  exposure:
#  include: "*"