server:
  port: 8888

spring:
  application:
    name: SpringCloudConfigServer
  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/HemantSondhiya/app-configuration
          username: ${USER_NAME}      # <--- Add your GitHub username
          password: ${USER_TOKEN} # <--- Add GitHub token
          default-label: main

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
